#' Overview and description of features.
#'
#' Note feature matrix column names and assay names of the MultiAssayExperiment object are the same.
#'
#' @name listFeatures
#' @return [data.table::data.table] containing an overview of the features.
#' @import data.table
#' @export
listFeatures <- function(){
  featList <- data.table(feature_name=c("Sequence",
                                        "Width",
                                        "Annot",
                                        "Binding_Patterns",
                                        "Promoter_Association",
                                        "C_score",
                                        "Cofactor_Binding",
                                        "CTCF-Signal",
                                        "Cooccuring_Motifs",
                                        "Associated_Motifs",
                                        "Inserts",
                                        "Weighted_Inserts",
                                        "Chi2_Dev_Profile",
                                        "ChromVAR_Scores",
                                        "ChromVAR_ATAC_Association",
                                        "MDS_Context",
                                        "Max_ATAC_Signal",
                                        "ATAC_Variance"),
                         description=c("CpG-density, GC-content and phastCon conservation scores",
                                       "Width in nucleotides of the site",
                                       "Extra user-provided numeric annotations for site",
                                       "Feature matrix w obtained by decomposing the ChIP-seq peak matrix by NMF (excluding specified TF)",
                                       "Pearson correlation and Cohen's Kappa between ATAC-signal of promoter(s) of the TF gene and the respective site",
                                       "Crowdedness of site, number of ChIP-seq peaks at the respective site (excluding specified TF)",
                                       "Mean ChIP-seq peak scores of cofactors at the respective site",
                                       "Maximum ChIP-seq peak scores of CTCF at the respective site",
                                       "Times the TF motif (and the cofactor motifs) appears within the respective site",
                                       "Motif matching scores of co-occuring and mutually exclusive motifs at the respective site",
                                       "Tn5 insertion counts around and within motif matches of the TF at the respective site",
                                       "Tn5 insertion counts around and within motif matches of the TF at the respective site weighted by insertion footprint profile",
                                       "Chi2-statistic of deviation of observed inserts at a site from the insertion footprint profile",
                                       "ChromVAR TF-Activity z-scores of TF and associated motifs",
                                       "Pearson correlation and Cohen's Kappa between ChromVAR z-scores of TF and ATAC-signal of the respective site across cellular contexts",
                                       "Projection of cellular context obtained Multidimensional Scaling of the ATAC-data of all cellular contexts",
                                       "Maximum (normalized) ATAC-signal of a site across all cellular contexts",
                                       "Variance of min-max normalized ATAC-signal at a site across cellular contexts"),
                         feature_type=c("site-Feature",
                                        "site-Feature",
                                        "site-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature"),
                         parameters=list(c("genome","phastCon"),
                                         c(""),
                                         c(""),
                                         c("nPatterns", "L1"),
                                         c(""),
                                         c(""),
                                         c(""),
                                         c(""),
                                         c(""),
                                         c("nMotifs"),
                                         c("margin", "shift"),
                                         c("margin", "profile", "symmetric", "stranded", "shift"),
                                         c("margin", "profile", "shift"),
                                         c("nVarSites", "niterations", "w", "bs"),
                                         c(""),
                                         c("nVarSites"),
                                         c(""),
                                         c("")),
                         feature_function_internal=c(".getSeqFeatures",
                                                     "",
                                                     "",
                                                     ".getBindingPatterns",
                                                     ".getAssociation",
                                                     ".getCrowdedness",
                                                     ".getCofactorBindings",
                                                     "",
                                                     ".getCoOccuringMotifs",
                                                     ".selectMotifs",
                                                     "getInsertionProfiles",
                                                     "getInsertionProfiles",
                                                     "getInsertionProfiles",
                                                     ".getChromVARScores, chromVAR::getBackgroundPeaks",
                                                     ".getChromVARScores, .getAssociation",
                                                     ".getContextProjection",
                                                     "",
                                                     ".getVariableSites"),
                         feature_function_exported=c("siteFeatures",
                                                     "siteFeatures",
                                                     "siteFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures"),
                         included_in_training=c(TRUE,
                                                FALSE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                FALSE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE),
                         context_normed=c(TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          FALSE,
                                          FALSE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE),
                         feature_matrix_column_names=list(paste(siteFeat, c(cpgDensFeatName, gcContFeatName, consScoreFeatName), sep="_"),
                                                          paste(siteFeat, widthFeatName, sep="_"),
                                                          paste(siteFeat, "<annotName>", sep="_"),
                                                          paste(tfFeat, c(tfPatternPrefix, contextPatternPrefix), sep="_"),
                                                          paste(tfFeat, promoterPrefix, c(assocPearsonPrefix, assocCohenPrefix), "<i>", sep="_"),
                                                          paste(tfFeat, cScoreFeatName, sep="_"),
                                                          paste(tfFeat, cofactorBindingPrefix, tfCofactorPrefix, "<i>", sep="_"),
                                                          paste(tfFeat, ctcfSigFeatName, sep="_"),
                                                          paste(tfFeat, c(coTfMotifPrefix, coCofactorMotifPrefix), "<i>", sep="_"),
                                                          paste(tfFeat, assocMotifPrefix, c("<tf_motif_name>", "<cofactor_motif_name>"), sep="_"),
                                                          paste(contextTfFeat, "tf", insertFeatName, c("within", "margin"), sep="_"),
                                                          paste(contextTfFeat, "tf", wInsertsFeatName, c("within", "margin"), sep="_"),
                                                          paste(contextTfFeat, devFeatName, sep="_"),
                                                          c(paste(contextTfFeat, chromVarScoreSuffix, tfActPrefix, "<i>", sep="_"),
                                                            paste(contextTfFeat, chromVarScoreSuffix, assocActPrefix, "<i>", sep="_")),
                                                          paste(contextTfFeat, c(assocPearsonPrefix, assocCohenPrefix), "<i>",chromVarAssocSuffix, "tf", sep="_"), # to be refactored
                                                          paste(contextFeat, mdsDimFeatName, 1:2, sep="_"),
                                                          paste(panContextFeat, maxAtacFeatName, sep="_"),
                                                          paste(panContextFeat, atacVarFeatName, sep="_")))

  return(featList)
}
