#' Overview and description of features.
#'
#' Note feature matrix column names and assay names of the MultiAssayExperiment object are the same.
#'
#' @name listFeatures
#' @return [data.table::data.table] containing an overview of the features.
#' @import data.table
#' @export
listFeatures <- function(){
  featList <- data.table(feature_name=c("Sequence",
                                        "Width",
                                        "Annot",
                                        "Binding_Patterns",
                                        "Promoter_Association",
                                        "C_score",
                                        "Cooccuring_Motifs",
                                        "Associated_Motifs",
                                        "Inserts",
                                        "Weighted_Inserts",
                                        "Cofactor_Inserts",
                                        "ChromVAR_Scores",
                                        "Cofactor_ChromVAR_Scores"),
                         description=c("CpG-density, GC-content and phastCon conservation scores",
                                       "Width in nucleotides of the site",
                                       "Extra user-provided numeric annotations for site",
                                       "Feature matrix w obtained by decomposing the ChIP-seq peak matrix by NMF (excluding specified TF)",
                                       "Pearson correlation and Cohen's Kappa between ATAC-signal of promoter(s) of the TF gene and the respective site",
                                       "Crowdedness of site, number of ChIP-seq peaks at the respective site (excluding specified TF)",
                                       "Times the TF motif (and the cofactor motifs) appears within the respective site",
                                       "Motif matching scores of co-occuring and mutually exclusive motifs at the respective site",
                                       "Tn5 insertion counts around and within motif matches of the TF at the respective site",
                                       "Tn5 insertion counts around and within motif matches of the TF at the respective site weighted by insertion footprint profile",
                                       "Tn5 insertion counts (weighted & unweighted) around and within motif matches of cofactors at the respective site",
                                       "ChromVAR TF-Activity z-scores of TF",
                                       "ChromVAR TF-Activity z-scores of cofactors"),
                         feature_type=c("site-Feature",
                                        "site-Feature",
                                        "site-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature"),
                         parameters=list(c("genome","phastCon"),
                                         c(""),
                                         c(""),
                                         c("nPatterns", "L1"),
                                         c(""),
                                         c(""),
                                         c(""),
                                         c("nMotifs"),
                                         c("margin", "shift"),
                                         c("profile", "symmetric", "stranded", "shift"),
                                         c("margin", "profile", "symmetric", "stranded", "shift"),
                                         c("subSample", "niterations", "w", "bs"),
                                         c("subSample", "niterations", "w", "bs")),
                         feature_function_internal=c(".getSeqFeatures",
                                                     "",
                                                     "",
                                                     ".getBindingPatterns",
                                                     ".getAssociation",
                                                     ".getNBindings",
                                                     ".getCoOccuringMotifs",
                                                     ".selectMotifs",
                                                     "getInsertionProfiles",
                                                     "getInsertionProfiles",
                                                     "getInsertionProfiles",
                                                     ".getChromVARScores, chromVAR::getBackgroundPeaks",
                                                     ".getChromVARScores, chromVAR::getBackgroundPeaks"),
                         feature_function_exported=c("siteFeatures",
                                                     "siteFeatures",
                                                     "siteFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures"),
                         included_in_training=c(TRUE,
                                                FALSE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                FALSE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE),
                         feature_matrix_column_names=list(c("siteFeat_cpg_density", "siteFeat_gc_content", "siteFeat_conservation_scores"),
                                                          c("siteFeat_width"),
                                                          c("siteFeat_<annotName>"),
                                                          c("tfFeat_pattern_tf_<i>", "tfFeat_pattern_context_<i>"),
                                                          c("tfFeat_Promoter_Pearson_<i>", "tfFeat_Promoter_Cohen_Kappa_<i>"),
                                                          c("tfFeat_n_chIP_peaks"),
                                                          c("tfFeat_n_cooccuring_tf_motifs", "tfFeat_n_cooccuring_cofactor_motifs_<i>"),
                                                          c("motif_<tf_name>", "motif_<cofactor_name>"),
                                                          c("contextFeat_<tf_name>_insert_counts_within","contextFeat_<tf_name>_insert_counts_margin"),
                                                          c("contextFeat_<tf_name>_weighted_insert_counts_within", "contextFeat_<tf_name>_weighted_insert_counts_margin"),
                                                          c("contextFeat_<cofactor_name>_insert_counts_within", "contextFeat_<cofactor_name>_insert_counts_margin",
                                                            "contextFeat_<cofactor_name>_weighted_insert_counts_within", "contextFeat_<cofactor_name>_weighted_insert_counts_margin"),
                                                          c("contextFeat_ChromVAR_score_<tf_name>", "ChromVAR_ATAC_Pearson_<tf_name>", "ChromVAR_ATAC_Cohen_Kappa_<tf_name>"),
                                                          c("contextFeat_ChromVAR_score_<cofactor_name>", "ChromVAR_ATAC_Pearson_<cofactor_name>", "ChromVAR_ATAC_Cohen_Kappa_<cofactor_name>")))

  return(featList)
}
