#' Overview and description of features.
#'
#' Provides an overview of the features.
#' Features are grouped into five types, which are explained in the following :
#' 1. site-Features: Specific for the sequence of a site.
#' 2. context-Features: Features specific for the ATAC-profile of a cellular context.
#' 3. pan-context-Features: Features of a site computed across ATAC-profiles of different cellular contexts.
#' 4. tf-Features: Features specific for a TF but not the cellular context.
#' 5. context-tf-Features: Features specific for a TF and the cellular context.
#'
#' Columns in the feature matrix (as returned by [TFBlearner::getFeatureMatrix]) are named the following:
#' `<featureType>_<featureName>` depending of the feature followed by (`<motifSuffix>, <i>, <normedSuffix>`).
#'
#' The column `parameters` contains the names of parameters for the respective feature, that can be passed to function computing the feature (listed in `feature_function_exported`).
#' The column `context_normed` indicates if the feature does not need to be normalized across cellular contexts when constructing the feature matrix.
#' Note feature matrix column names and assay names of the MultiAssayExperiment object are the same.
#'
#' @name listFeatures
#' @return [data.table::data.table] containing an overview of the features.
#' @import data.table
#' @export
listFeatures <- function(){
  motifPrefices <- c(priorMotifPrefix, tfMotifPrefix, tfCofactorMotifPrefix,
                     selMotifPrefix, ctcfMotifPrefix)
  featList <- data.table(feature_name=c("Sequence",
                                        "Width",
                                        "Annot",
                                        "Binding_Patterns",
                                        "Promoter_Association",
                                        "C_Score",
                                        "Cofactor_Binding",
                                        "CTCF_Signal",
                                        "Cooccuring_Motifs",
                                        "Associated_Motifs",
                                        "Associated_Motif_Activity",
                                        "Inserts",
                                        "Weighted_Inserts",
                                        "Chi2_Dev_Profile",
                                        "ChromVAR_Scores",
                                        "Fragment_Counts",
                                        "MDS_Context",
                                        "Max_ATAC_Signal",
                                        "ATAC_Variance"),
                         description=c("CpG-density, GC-content and phastCon conservation scores",
                                       "Width in nucleotides of the site",
                                       "Extra user-provided numeric annotations for site",
                                       "Feature matrix w obtained when decomposing the ChIP-seq peak matrix by NMF (excluding the specified TF)",
                                       "Pearson correlation and Cohen's Kappa between ATAC-signal of promoter(s) of the TF gene and the respective site",
                                       "Crowdedness of site, number of ChIP-seq peaks at the respective site (excluding specified TF)",
                                       "Mean ChIP-seq peak scores of cofactors at the respective site",
                                       "Maximum ChIP-seq peak scores of CTCF at the respective site",
                                       "Times the TF motif (and the cofactor motifs) appears within the respective site",
                                       "Motif matching scores of co-occuring and mutually exclusive motifs at the respective site",
                                       "Pearson correlation between ChromVAR z-scores (of TF and associated motifs) and ATAC-signal of the respective site across cellular contexts",
                                       "Tn5 insertion counts around and within motif matches of the TF at the respective site",
                                       "Tn5 insertion counts around and within motif matches of the TF at the respective site weighted by insertion footprint profile",
                                       "Chi2-statistic of deviation of observed inserts at a site from the insertion footprint profile",
                                       "ChromVAR TF-Activity z-scores of TF and associated motifs",
                                       "Counts of different fragment types (nucleosome-free, mononucleosome, etc.). Split in counts of total overlaps and insertions at a site",
                                       "Projection of cellular context obtained Multidimensional Scaling of the ATAC-data of all cellular contexts",
                                       "Maximum (normalized) ATAC-signal of a site across all cellular contexts",
                                       "Variance of min-max normalized ATAC-signal at a site across cellular contexts"),
                         feature_type=c("site-Feature",
                                        "site-Feature",
                                        "site-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-tf-Feature",
                                        "context-Feature",
                                        "context-Feature",
                                        "pan-context-Feature",
                                        "pan-context-Feature"),
                         parameters=list(c("genome","phastCon"),
                                         c(""),
                                         c(""),
                                         c("nPatterns", "L1"),
                                         c(""),
                                         c(""),
                                         c(""),
                                         c(""),
                                         c(""),
                                         c("nMotifs"),
                                         c("nMotifs"),
                                         c("margin", "shift"),
                                         c("margin", "profile", "symmetric", "stranded", "shift"),
                                         c("margin", "profile", "shift"),
                                         c("niterations", "w", "bs"),
                                         c(""),
                                         c("nVarSites"),
                                         c(""),
                                         c("")),
                         feature_function_internal=c(".getSeqFeatures",
                                                     "",
                                                     "",
                                                     ".getBindingPatterns",
                                                     ".getAssociation",
                                                     ".getCrowdedness",
                                                     ".getCofactorBindings",
                                                     "",
                                                     ".getCoOccuringMotifs",
                                                     ".selectMotifs",
                                                     ".CV2localAssociation, .selectMotifs",
                                                     "getInsertionProfiles",
                                                     "getInsertionProfiles",
                                                     "getInsertionProfiles",
                                                     ".CVwrapper, chromVAR::computeExpectations, chromVAR::getBackgroundPeaks, chromVAR::computeDeviations",
                                                     ".mapAtacData",
                                                     ".getContextProjection",
                                                     "",
                                                     ".getVariableSites"),
                         feature_function_exported=c("siteFeatures",
                                                     "siteFeatures",
                                                     "siteFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "tfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextTfFeatures",
                                                     "contextFeatures",
                                                     "contextFeatures",
                                                     "panContextFeatures",
                                                     "panContextFeatures"),
                         included_in_training=c(TRUE,
                                                FALSE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE,
                                                TRUE),
                         context_normed=c(TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          TRUE,
                                          FALSE,
                                          FALSE,
                                          TRUE,
                                          TRUE,
                                          FALSE,
                                          TRUE,
                                          TRUE,
                                          TRUE),
                         feature_matrix_column_names=list(paste(siteFeat, c(cpgDensFeatName, gcContFeatName, consScoreFeatName), sep="_"),
                                                          paste(siteFeat, widthFeatName, sep="_"),
                                                          paste(siteFeat, "<annotName>", sep="_"),
                                                          paste(tfFeat, c(patTfFeatName, patContextFeatName), "<i>", sep="_"),
                                                          paste(tfFeat, promFeatName, "<i>", sep="_"),
                                                          paste(tfFeat, cScoreFeatName, sep="_"),
                                                          paste(tfFeat, coBindFeatName, gsub(motifAffix, "", tfCofactorMotifPrefix), "<i>", sep="_"),
                                                          paste(tfFeat, ctcfFeatName, sep="_"),
                                                          paste(tfFeat, coCountFeatName, c(tfMotifPrefix, tfCofactorMotifPrefix), "<i>", sep="_"),
                                                          paste(tfFeat, motifFeatName, motifPrefices, "<i>", sep="_"),
                                                          paste(tfFeat, actAssocFeatName, motifPrefices, "<i>", sep="_"),
                                                          paste(contextTfFeat, paste(insertFeatName, c("within", "margin"), sep="."),
                                                                tfMotifPrefix,"<i>", sep="_"),
                                                          paste(contextTfFeat, paste(wInsertsFeatName, c("within", "margin"), sep="."),
                                                                tfMotifPrefix, "<i>", sep="_"),
                                                          paste(contextTfFeat, devFeatName, sep="_"),
                                                          c(paste(contextTfFeat, chromVarFeatName, motifPrefices, "<i>", sep="_")),
                                                          c(paste(contextFeat,c(totalOverlapsFeatName, totalInsertsFeatName,
                                                                              paste(typeNames, insertsAffix, sep="."),
                                                                              paste(typeNames, overlapsAffix, sep=".")),
                                                                sep="_")),
                                                          paste(contextFeat, mdsDimFeatName, 1:2, sep="_"),
                                                          paste(panContextFeat, maxAtacFeatName, sep="_"),
                                                          paste(panContextFeat, atacVarFeatName, sep="_")))

  return(featList)
}
